### ISSUE TITLE
vertical text option

### ISSUE THREAD

**Issue by Omar-Abdul-Azeez** [KamWithK/exSTATic#13]
there's not much to say here...

**Comment by KamWithK** [comment]
People who want hyper specific features which only a few people will use should try to implement and create a PR themselves
I have a branch where I was experimenting with it a long while ago (before the first public release) but didn't make any progress unfortunately
That being said maybe I will do this (I would like to eventually), but it of course would again be one of those things which only gets added after all the important stuff which everyone wants
