### ISSUE TITLE
Icons not showing up?

### ISSUE THREAD

**Issue by FirionHope** [KamWithK/exSTATic#15]
Just installed the extension and tried it out. While the tracking seems to work the icons aren't showing up, just descriptions of what they should be

for example https://i.imgur.com/3sDgTGI.png

**Comment by KamWithK** [comment]
You're probably using an old outdated browser
Shouldn't happen on the latest Chrome or Firefox 😅

**Comment by FirionHope** [comment]
No I'm using chrome, checked today and its fully updated but it couldn't of been that old when I made the post since I leave it on auto update. The extension was also missing when I went to check just now but after I reinstalled it now seems to work fine.

**Comment by KamWithK** [comment]
It could've just taken a bit longer for the Chrome patch to hit your browser
There was a very recent Chrome patch which added support for a bug fix which allowed the latest exSTATic releases to easily load fonts/images which previous versions didn't have
