### ISSUE TITLE
Any way to make this work with mokuro .pdf?

### ISSUE THREAD

**Issue by Whitesttax** [KamWithK/exSTATic#19]
I recently finished mokuroing all my manga, like hundreds, but it's all in .pdf since I read on mobile as well. 
I use Kavita (https://github.com/Kareadita/Kavita) to read on the browser. 
Is there anything I can do?

**Comment by KamWithK** [comment]
This would require a new integration, likely worth creating as a lot of people read from pdf's like using Kavita
I currently don't have time to work on this unfortunately, but if you'd like to create it yourself I'm open to accept PRs 😄
Feel free to @ or dm me on Discord further if you'd like to work on creating a new integration
