### ISSUE TITLE
Integration with animebook?

### ISSUE THREAD

**Issue by FirionHope** [KamWithK/exSTATic#20]
So far this program covers Visual Novels, Manga, and Light Novels/books. Games aren't really able to be covered given how they work. So that just leaves covering anime as a learning source. I personally use this to watch anime, I don't know the technical details but I wonder if at some point it might be possible to scrape data from it aswell? : https://github.com/animebook/animebook.github.io As an alternative there's also this: https://github.com/ripose-jp/Memento but I don't have any personal experience. So overall just a question/suggestion for a feature to maybe add one day

**Comment by KamWithK** [comment]
I'm open to others working on this and contributing it but at this point in time I don't have any personal interest in anime integrations
