### ISSUE TITLE
FireFox forces insecure ws websockets to upgrade to secure wss causing it to never connect

### ISSUE THREAD

**Issue by Mehhhjp** [KamWithK/exSTATic#23]
I don't know exactly what is wrong with version 0.0.9, but unfortunately it can't receive information from the textractor. Until yesterday everything was normal, but after this update this failure appeared. I have now gone back to version 0.0.8, and it is still working without any problems. Please do know that I love your project. It's very simple, but the thought of coding something like this makes me nauseous. That being said, for heaven's sake, please test the versions properly before updating them
I almost suffered a heart attack when it didn't work here

**Comment by ziodyne0** [comment]
+1 was driving me crazy trying to figure out what happened lol. A downgrade to 0.0.8 fixed the issue for me too.

**Comment by KamWithK** [comment]
I plan to look into this tomorrow
I and one other person did test it out without these issues so I'm not sure why this actually happened
I'll have a deep dive into it and hopefully be able to update and fix the issue tomorrow

**Comment by KamWithK** [comment]
The latest release fixes this issue, it should be up relatively soon
I haven't managed to reproduce the issue on Chromium but just in case it does happen there in the future I've applied to manifest fix to both FireFox and Chrome
