### ISSUE TITLE
have pause button

### ISSUE THREAD

**Issue by Helmasko** [KamWithK/exSTATic#28]
I think it would be useful to have a way to pause the timer like in https://anacreondjt.gitlab.io/texthooker.html
I for one would benefit by it by pausing it to do lookups or when stopping playing.
My current workaround is by shortening the max AFK secs but its annoying. There is no optimal time that I can set that will alleviate this pain

**Comment by KamWithK** [comment]
There already is actually already a very easy and convenient way to do this which is double click pause/resume

It is better than having a dedicated button as you don't need to move to the top of the page or anything, you can just double click almost anywhere (although if you were not aware of this I can imagine it wouldn't be something you would randomly test, but nonetheless it does the job very well imo)
