### ISSUE TITLE
Adjust idle timer within Mokuro when using exSTATic

### ISSUE THREAD

**Issue by wholesalegerbils** [KamWithK/exSTATic#4]
Just wanted to say, briefly, that the extension is awesome, really enjoying it so far!  I think this is more in line with a feature request rather than a bug but I find that when using the extension here:  https://kamwithk.github.io/exSTATic/tracker.html you can adjust the "max AFK time" as well as the "inactivity blur" whereas when reading a Mokuro generated .html there doesn't seem to be any way to do that.  Due to me not being a great reader I find that the page enters "idle" which blurs the whole page until I double click again to clear the idle status pretty often.  

Edit:  I'm using the latest "firefox" build from the extensions section if that matters.

**Comment by KamWithK** [comment]
Hey @wholesalegerbils I'm aware that there are currently some limitations on Mokuro
Eventually I'll get onto this but for now I have more important updates (for example Manifest V3 support so I can release onto Chrome).
Thanks for you understanding and thanks for the feature request 👍

**Comment by FirionHope** [comment]
I wanted to add that as much as I enjoy this program, this is also my biggest annoyance by far, and if you do get the time at some point I would also love that feature. Even just adjusting the default timeout to be considerably longer would be enough, or making it so the blur doesn't apply or something. Using as it is a decent portions of the pages I end up reading have it blur out part way through and I have to click around for a while for it to unblur. Makes me feel like I have to rush and can't enjoy the art

**Comment by KamWithK** [comment]
I 100% agree with you guys, thanks for commenting on this
I closed this issue not because it isn't planned/I don't value it, but rather because it's a planned new feature for the new exSTATic web version
There will be a settings page with a tab per integration (i.e. one for VNs, one for Mokuro and one for TTU), so you can modify the settings individually as-expected

**Comment by FirionHope** [comment]
Oh that sounds really handy and cool, I'm looking forward to it!
