### ISSUE TITLE
use an offline page instead of hosting it on github

### ISSUE THREAD

**Issue by Omar-Abdul-Azeez** [KamWithK/exSTATic#6]
like yomichan which has a local page you can use when searching something instead of having to search for a place to type it, including tracker and stats pages in the extension would be better.

**Comment by KamWithK** [comment]
This is already a feature
You just need to format the path to the file correctly (refer to the [manifest](https://github.com/KamWithK/exSTATic/blob/master/manifest.json#L22))

For example if you have the file `tracker.html` within a folder called `exSTATic`, the extension will detect it and inject in correctly

**Comment by Omar-Abdul-Azeez** [comment]
slight clarification... it needs to be inside a folder inside `exSTATic` inside another folder `file:///*/exSTATic/*/tracker.html`
you might want to change that to `file:///(.*/)?esSTATic/(.*/)?tracker.html` if that's how you intended it to be.
