### ISSUE TITLE
reset stats completely or delete specific entries

### ISSUE THREAD

**Issue by Omar-Abdul-Azeez** [KamWithK/exSTATic#7]

**Comment by KamWithK** [comment]
Currently the best/easiest way to do this is to just  export your stats, delete the extension and reimport an edited version with whatever you want (or if you want nothing then just don't import/export)
Not the greatest but I'm currently working on several larger features right now so this doesn't really have a high priority for me right now

**Comment by musjj** [comment]
Is there now an easy way to reset the tracker page? I want to start fresh on every new day.
